### ISSUE TITLE
please help

### ISSUE THREAD

**Issue by Efileep** [ShafiqSadat/HamsterKeyGen#17]
bro i opened the .exe and select the game & nubmers. but when i enter the proxy(empty or with proxy) the script did something and then that's quickly closed. please help and say what i do :(
( i just created proxy.txt in the HamsterKeyGen-main folder )

Traceback (most recent call last):
  File "main.py", line 139, in <module>
    keys, game_name = asyncio.run(main(game_choice, key_count, proxies))
  File "asyncio\runners.py", line 44, in run
  File "asyncio\base_events.py", line 616, in run_until_complete
  File "main.py", line 125, in main
    keys = await asyncio.gather(*tasks)
  File "main.py", line 98, in generate_key_process
    client_token = await login(client_id, app_token, proxy)
  File "main.py", line 63, in login
    async with httpx.AsyncClient(proxies=proxy) as client:
  File "httpx\_client.py", line 1429, in __init__
  File "httpx\_client.py", line 229, in _get_proxy_map
  File "httpx\_config.py", line 336, in __init__
ValueError: Unknown scheme for proxy URL URL('socks4://proxy-server:1080')
[11780] Failed to execute script 'main' due to unhandled exception!

**Comment by ShafiqSadat** [comment]
if you don't have proxies just press enter and don't create a proxy.txt file !

**Comment by Efileep** [comment]
> if you don't have proxies just press enter and don't create a proxy.txt file !

ok. i deleted txt and run without proxy but it not working. like before it's closes

**Comment by ShafiqSadat** [comment]
Check out new version and let me know if your problem has solved or not!
