### ISSUE TITLE
i m not able to use proxies

### ISSUE THREAD

**Issue by SarcasticBalak** [ShafiqSadat/HamsterKeyGen#20]

**Comment by ShafiqSadat** [comment]
Can you give me more details?

**Comment by SarcasticBalak** [comment]
File "C:\Users\itzan\AppData\Local\Programs\Python\Python310\lib\site-packages\httpx\_transports\default.py", line 69, in map_httpcore_exceptions
    yield
  File "C:\Users\itzan\AppData\Local\Programs\Python\Python310\lib\site-packages\httpx\_transports\default.py", line 373, in handle_async_request
    resp = await self._pool.handle_async_request(req)
  File "C:\Users\itzan\AppData\Local\Programs\Python\Python310\lib\site-packages\httpcore\_async\connection_pool.py", line 216, in handle_async_request
    raise exc from None
  File "C:\Users\itzan\AppData\Local\Programs\Python\Python310\lib\site-packages\httpcore\_async\connection_pool.py", line 196, in handle_async_request
    response = await connection.handle_async_request(
  File "C:\Users\itzan\AppData\Local\Programs\Python\Python310\lib\site-packages\httpcore\_async\http_proxy.py", line 344, in handle_async_request
    return await self._connection.handle_async_request(request)
  File "C:\Users\itzan\AppData\Local\Programs\Python\Python310\lib\site-packages\httpcore\_async\http11.py", line 143, in handle_async_request
    raise exc
  File "C:\Users\itzan\AppData\Local\Programs\Python\Python310\lib\site-packages\httpcore\_async\http11.py", line 113, in handle_async_request
    ) = await self._receive_response_headers(**kwargs)
  File "C:\Users\itzan\AppData\Local\Programs\Python\Python310\lib\site-packages\httpcore\_async\http11.py", line 186, in _receive_response_headers
    event = await self._receive_event(timeout=timeout)
  File "C:\Users\itzan\AppData\Local\Programs\Python\Python310\lib\site-packages\httpcore\_async\http11.py", line 224, in _receive_event
    data = await self._network_stream.read(
  File "C:\Users\itzan\AppData\Local\Programs\Python\Python310\lib\site-packages\httpcore\_backends\anyio.py", line 32, in read
    with map_exceptions(exc_map):
  File "C:\Users\itzan\AppData\Local\Programs\Python\Python310\lib\contextlib.py", line 153, in __exit__
    self.gen.throw(typ, value, traceback)
  File "C:\Users\itzan\AppData\Local\Programs\Python\Python310\lib\site-packages\httpcore\_exceptions.py", line 14, in map_exceptions
    raise to_exc(exc) from exc
httpcore.ReadTimeout

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\itzan\OneDrive\Desktop\gol\HamsterKeyGen-main\main.py", line 147, in <module>
    keys, game_name = asyncio.run(main(game_choice, key_count, proxies))
  File "C:\Users\itzan\AppData\Local\Programs\Python\Python310\lib\asyncio\runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "C:\Users\itzan\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 641, in run_until_complete
    return future.result()
  File "C:\Users\itzan\OneDrive\Desktop\gol\HamsterKeyGen-main\main.py", line 133, in main
    keys = await asyncio.gather(*tasks)
  File "C:\Users\itzan\OneDrive\Desktop\gol\HamsterKeyGen-main\main.py", line 124, in generate_key_process
    key = await generate_key(client_token, promo_id, proxies)
  File "C:\Users\itzan\OneDrive\Desktop\gol\HamsterKeyGen-main\main.py", line 98, in generate_key
    response = await client.post(
  File "C:\Users\itzan\AppData\Local\Programs\Python\Python310\lib\site-packages\httpx\_client.py", line 1892, in post
    return await self.request(
  File "C:\Users\itzan\AppData\Local\Programs\Python\Python310\lib\site-packages\httpx\_client.py", line 1574, in request
    return await self.send(request, auth=auth, follow_redirects=follow_redirects)
  File "C:\Users\itzan\AppData\Local\Programs\Python\Python310\lib\site-packages\httpx\_client.py", line 1661, in send
    response = await self._send_handling_auth(
  File "C:\Users\itzan\AppData\Local\Programs\Python\Python310\lib\site-packages\httpx\_client.py", line 1689, in _send_handling_auth
    response = await self._send_handling_redirects(
  File "C:\Users\itzan\AppData\Local\Programs\Python\Python310\lib\site-packages\httpx\_client.py", line 1726, in _send_handling_redirects
    response = await self._send_single_request(request)
  File "C:\Users\itzan\AppData\Local\Programs\Python\Python310\lib\site-packages\httpx\_client.py", line 1763, in _send_single_request
    response = await transport.handle_async_request(request)
  File "C:\Users\itzan\AppData\Local\Programs\Python\Python310\lib\site-packages\httpx\_transports\default.py", line 372, in handle_async_request
    with map_httpcore_exceptions():
  File "C:\Users\itzan\AppData\Local\Programs\Python\Python310\lib\contextlib.py", line 153, in __exit__
    self.gen.throw(typ, value, traceback)
  File "C:\Users\itzan\AppData\Local\Programs\Python\Python310\lib\site-packages\httpx\_transports\default.py", line 86, in map_httpcore_exceptions
    raise mapped_exc(message) from exc
httpx.ReadTimeout
