### ISSUE TITLE
Error when trying to generate more than 4 keys

### ISSUE THREAD

**Issue by l3est** [ShafiqSadat/HamsterKeyGen#22]
I'm trying to generate 40 keys after the new update but I get this error when I enter anything > 4:

Enter the game number: 4
Enter the number of keys to generate: 40
Enter the proxy file path (leave empty to use 'proxy.txt'):
2024-08-08 23:48:54 | INFO     | 52 - Proxy file proxy.txt not found. No proxies will be used.
2024-08-08 23:48:54 | INFO     | 146 - Generating 40 key(s) for Train Miner using proxies from no proxies
Traceback (most recent call last):
  File "C:\Portable\HamsterKeyGen\main.py", line 147, in <module>
    keys, game_name = asyncio.run(main(game_choice, key_count, proxies))
  File "C:\Users\l3eyo\AppData\Local\Programs\Python\Python310\lib\asyncio\runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "C:\Users\l3eyo\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 649, in run_until_complete
    return future.result()
  File "C:\Portable\HamsterKeyGen\main.py", line 133, in main
    keys = await asyncio.gather(*tasks)
  File "C:\Portable\HamsterKeyGen\main.py", line 109, in generate_key_process
    client_token = await login(client_id, app_token, proxies)
  File "C:\Portable\HamsterKeyGen\main.py", line 76, in login
    logger.error(f"Failed to login (attempt {attempt + 1}/{retries}): {e.response.json()}")
  File "C:\Users\l3eyo\AppData\Local\Programs\Python\Python310\lib\site-packages\httpx\_models.py", line 764, in json
    return jsonlib.loads(self.content, **kwargs)
  File "C:\Users\l3eyo\AppData\Local\Programs\Python\Python310\lib\json\__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "C:\Users\l3eyo\AppData\Local\Programs\Python\Python310\lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "C:\Users\l3eyo\AppData\Local\Programs\Python\Python310\lib\json\decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

**Comment by ShafiqSadat** [comment]
You should use proxies!
