### ISSUE TITLE
Good afternoon. What could be the problem?

### ISSUE THREAD

**Issue by lexad1d** [ShafiqSadat/HamsterKeyGen#25]
1: Riding Extreme 3D   
2: Chain Cube 2048     
3: My Clone Army       
4: Train Miner
Enter the game number: 4
Enter the number of keys to generate: 5
Enter the proxy file path (leave empty to use 'proxy.txt'): 
2024-08-09 16:58:18 | INFO     | 143 - Generating 5 key(s) for Train Miner using proxy from proxy.txt
Traceback (most recent call last):
  File "F:\взлом игр\main.py", line 144, in <module>
    keys, game_name = asyncio.run(main(game_choice, key_count, proxy))
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Леша\AppData\Local\Programs\Python\Python312\Lib\asyncio\runners.py", line 194, in run
    return runner.run(main)
           ^^^^^^^^^^^^^^^^
  File "C:\Users\Леша\AppData\Local\Programs\Python\Python312\Lib\asyncio\runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Леша\AppData\Local\Programs\Python\Python312\Lib\asyncio\base_events.py", line 687, in run_until_complete       
    return future.result()
    keys = await asyncio.gather(*tasks)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\взлом игр\main.py", line 105, in generate_key_process
    logger.error(f"Failed to login: {e.response.json()}")
                                     ^^^^^^^^^^^^^^^^^
  File "C:\Users\Леша\AppData\Local\Programs\Python\Python312\Lib\site-packages\httpx\_models.py", line 764, in json
    return jsonlib.loads(self.content, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Леша\AppData\Local\Programs\Python\Python312\Lib\json\__init__.py", line 346, in loads
    return _default_decoder.decode(s)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Леша\AppData\Local\Programs\Python\Python312\Lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Леша\AppData\Local\Programs\Python\Python312\Lib\json\decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

**Comment by ShafiqSadat** [comment]
I think problem is with your proxy server!

**Comment by lexad1d** [comment]
1. I tried to replace the proxy and the error remained the same.
2 . I deleted the proxy and the error is the same, has not changed=(

**Comment by Officialkarz** [comment]
what is your python version ? download 3.7.5

**Comment by unkby** [comment]
> I think problem is with your proxy server!

Maybe you can configure the script to work in 1-2-3...99 connections to the server? then I think many problems will disappear

**Comment by ShafiqSadat** [comment]
Try with proxy!
