### ISSUE TITLE
how to fix

### ISSUE THREAD

**Issue by nnaskz** [ShafiqSadat/HamsterKeyGen#6]
C:\Users\RouFok OS\Videos\socka\HamsterKeyGen>python main.py
Select a game:
1: Riding Extreme 3D
2: Chain Cube 2048
3: My Clone Army
4: Train Miner
Enter the game number: 2
Enter the number of keys to generate: 2
Enter the proxy file path (leave empty to use 'proxy.txt'):
2024-08-06 20:04:29 | INFO     | 143 - Generating 2 key(s) for Chain Cube 2048 using proxy from proxy.txt
Traceback (most recent call last):
  File "C:\Users\RouFok OS\Videos\socka\HamsterKeyGen\main.py", line 144, in <module>
    keys, game_name = asyncio.run(main(game_choice, key_count, proxy))
  File "C:\Users\RouFok OS\AppData\Local\Programs\Python\Python310\lib\asyncio\runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "C:\Users\RouFok OS\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 641, in run_until_complete
    return future.result()
  File "C:\Users\RouFok OS\Videos\socka\HamsterKeyGen\main.py", line 129, in main
    keys = await asyncio.gather(*tasks)
  File "C:\Users\RouFok OS\Videos\socka\HamsterKeyGen\main.py", line 103, in generate_key_process
    client_token = await login(client_id, app_token, proxy)
  File "C:\Users\RouFok OS\Videos\socka\HamsterKeyGen\main.py", line 67, in login
    response = await client.post(
  File "C:\Users\RouFok OS\AppData\Local\Programs\Python\Python310\lib\site-packages\httpx\_client.py", line 1848, in post
    return await self.request(
  File "C:\Users\RouFok OS\AppData\Local\Programs\Python\Python310\lib\site-packages\httpx\_client.py", line 1530, in request
    return await self.send(request, auth=auth, follow_redirects=follow_redirects)
  File "C:\Users\RouFok OS\AppData\Local\Programs\Python\Python310\lib\site-packages\httpx\_client.py", line 1617, in send
    response = await self._send_handling_auth(
  File "C:\Users\RouFok OS\AppData\Local\Programs\Python\Python310\lib\site-packages\httpx\_client.py", line 1645, in _send_handling_auth
    response = await self._send_handling_redirects(
  File "C:\Users\RouFok OS\AppData\Local\Programs\Python\Python310\lib\site-packages\httpx\_client.py", line 1682, in _send_handling_redirects
    response = await self._send_single_request(request)
  File "C:\Users\RouFok OS\AppData\Local\Programs\Python\Python310\lib\site-packages\httpx\_client.py", line 1719, in _send_single_request
    response = await transport.handle_async_request(request)
  File "C:\Users\RouFok OS\AppData\Local\Programs\Python\Python310\lib\site-packages\httpx\_transports\default.py", line 353, in handle_async_request
    resp = await self._pool.handle_async_request(req)
  File "C:\Users\RouFok OS\AppData\Local\Programs\Python\Python310\lib\site-packages\httpcore\_async\connection_pool.py", line 262, in handle_async_request
    raise exc
  File "C:\Users\RouFok OS\AppData\Local\Programs\Python\Python310\lib\site-packages\httpcore\_async\connection_pool.py", line 245, in handle_async_request
    response = await connection.handle_async_request(request)
  File "C:\Users\RouFok OS\AppData\Local\Programs\Python\Python310\lib\site-packages\httpcore\_async\socks_proxy.py", line 294, in handle_async_request
    raise exc
  File "C:\Users\RouFok OS\AppData\Local\Programs\Python\Python310\lib\site-packages\httpcore\_async\socks_proxy.py", line 244, in handle_async_request
    await _init_socks5_connection(**kwargs)
  File "C:\Users\RouFok OS\AppData\Local\Programs\Python\Python310\lib\site-packages\httpcore\_async\socks_proxy.py", line 97, in _init_socks5_connection
    response = conn.receive_data(incoming_bytes)
  File "C:\Users\RouFok OS\AppData\Local\Programs\Python\Python310\lib\site-packages\socksio\socks5.py", line 382, in receive_data
    reply = SOCKS5Reply.loads(data)
  File "C:\Users\RouFok OS\AppData\Local\Programs\Python\Python310\lib\site-packages\socksio\socks5.py", line 262, in loads
    addr=decode_address(AddressType.from_socks5_atype(atype), data[4:-2]),
TypeError: unhashable type: 'bytearray'
Exception ignored in: <function _ProactorBasePipeTransport.__del__ at 0x0000014FA509BA30>
Traceback (most recent call last):
  File "C:\Users\RouFok OS\AppData\Local\Programs\Python\Python310\lib\asyncio\proactor_events.py", line 116, in __del__
    self.close()
  File "C:\Users\RouFok OS\AppData\Local\Programs\Python\Python310\lib\asyncio\proactor_events.py", line 108, in close
    self._loop.call_soon(self._call_connection_lost, None)
  File "C:\Users\RouFok OS\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 745, in call_soon
    self._check_closed()
  File "C:\Users\RouFok OS\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 510, in _check_closed
    raise RuntimeError('Event loop is closed')
RuntimeError: Event loop is closed
Exception ignored in: <function _ProactorBasePipeTransport.__del__ at 0x0000014FA509BA30>
Traceback (most recent call last):
  File "C:\Users\RouFok OS\AppData\Local\Programs\Python\Python310\lib\asyncio\proactor_events.py", line 116, in __del__
  File "C:\Users\RouFok OS\AppData\Local\Programs\Python\Python310\lib\asyncio\proactor_events.py", line 108, in close
  File "C:\Users\RouFok OS\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 745, in call_soon
  File "C:\Users\RouFok OS\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 510, in _check_closed
RuntimeError: Event loop is closed

C:\Users\RouFok OS\Videos\socka\HamsterKeyGen>

**Comment by ShafiqSadat** [comment]
Can you try to use without proxy or other proxy protocol?

**Comment by nnaskz** [comment]
I tried without proxy, it works. I'll try another protocol now.

**Comment by nnaskz** [comment]
What format should I specify if I have private proxies?

**Comment by ShafiqSadat** [comment]
read readme file!

**Comment by ShafiqSadat** [comment]
https://github.com/ShafiqSadat/HamsterKeyGen?tab=readme-ov-file#using-proxies

**Comment by nnaskz** [comment]
my proxy has a username and password.

**Comment by nnaskz** [comment]
and it says without them, that is. ip:port
I'm doing it. login:pass@ip:port

**Comment by nnaskz** [comment]
thank you, friend!

**Comment by ShafiqSadat** [comment]
Can you check proxy with this format?

http://username:password@proxy-server:port

**Comment by nnaskz** [comment]
okay, wait

**Comment by nnaskz** [comment]
2024-08-06 20:32:39 | INFO     | 143 - Generating 5 key(s) for Train Miner using proxy from proxy.txt
Traceback (most recent call last):
  File "C:\Users\RouFok OS\Videos\socka\HamsterKeyGen\main.py", line 144, in <module>
    keys, game_name = asyncio.run(main(game_choice, key_count, proxy))
  File "C:\Users\RouFok OS\AppData\Local\Programs\Python\Python310\lib\asyncio\runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "C:\Users\RouFok OS\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 641, in run_until_complete
    return future.result()
  File "C:\Users\RouFok OS\Videos\socka\HamsterKeyGen\main.py", line 129, in main
    keys = await asyncio.gather(*tasks)
  File "C:\Users\RouFok OS\Videos\socka\HamsterKeyGen\main.py", line 103, in generate_key_process
    client_token = await login(client_id, app_token, proxy)
  File "C:\Users\RouFok OS\Videos\socka\HamsterKeyGen\main.py", line 66, in login
    async with httpx.AsyncClient(proxies=proxy) as client:
  File "C:\Users\RouFok OS\AppData\Local\Programs\Python\Python310\lib\site-packages\httpx\_client.py", line 1395, in __init__
    proxy_map = self._get_proxy_map(proxies, allow_env_proxies)
  File "C:\Users\RouFok OS\AppData\Local\Programs\Python\Python310\lib\site-packages\httpx\_client.py", line 228, in _get_proxy_map
    proxy = Proxy(url=proxies) if isinstance(proxies, (str, URL)) else proxies
  File "C:\Users\RouFok OS\AppData\Local\Programs\Python\Python310\lib\site-packages\httpx\_config.py", line 332, in __init__
    url = URL(url)
  File "C:\Users\RouFok OS\AppData\Local\Programs\Python\Python310\lib\site-packages\httpx\_urls.py", line 113, in __init__
    self._uri_reference = urlparse(url, **kwargs)
  File "C:\Users\RouFok OS\AppData\Local\Programs\Python\Python310\lib\site-packages\httpx\_urlparse.py", line 160, in urlparse
    raise InvalidURL("Invalid non-printable ASCII character in URL")
httpx.InvalidURL: Invalid non-printable ASCII character in URL

**Comment by nnaskz** [comment]
![изображение](https://github.com/user-attachments/assets/975d636a-2111-44ca-b9c4-514809864776)

**Comment by nnaskz** [comment]
I fixed it with gpt.

**Comment by ShafiqSadat** [comment]
Can you send me your fixed code?

**Comment by nnaskz** [comment]
Wait please, I want to add a proxy checker for 5.

**Comment by ShafiqSadat** [comment]
Fixed, added support for multi proxies!
