### ISSUE TITLE
can you help me bro? 

### ISSUE THREAD

**Issue by xaozzzz** [ShafiqSadat/HamsterKeyGen#7]
Select a game:
1: Riding Extreme 3D
2: Chain Cube 2048
3: My Clone Army
4: Train Miner
Enter the game number: 2
Enter the number of keys to generate: 25
Enter the proxy file path (leave empty to use 'proxy.txt'): 
2024-08-06 22:53:32 | INFO     | 143 - Generating 25 key(s) for Chain Cube 2048 using proxy from proxy.txt
Traceback (most recent call last):
  File "C:\Users\danil\Desktop\ProjectsPython\HamsterKeys\venv\Lib\site-packages\httpx\_transports\default.py", line 69, in map_httpcore_exceptions
    yield
  File "C:\Users\danil\Desktop\ProjectsPython\HamsterKeys\venv\Lib\site-packages\httpx\_transports\default.py", line 373, in handle_async_request
    resp = await self._pool.handle_async_request(req)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\danil\Desktop\ProjectsPython\HamsterKeys\venv\Lib\site-packages\httpcore\_async\connection_pool.py", line 216, in handle_async_request
    raise exc from None
  File "C:\Users\danil\Desktop\ProjectsPython\HamsterKeys\venv\Lib\site-packages\httpcore\_async\connection_pool.py", line 196, in handle_async_request
    response = await connection.handle_async_request(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\danil\Desktop\ProjectsPython\HamsterKeys\venv\Lib\site-packages\httpcore\_async\socks_proxy.py", line 296, in handle_async_request
    raise exc
  File "C:\Users\danil\Desktop\ProjectsPython\HamsterKeys\venv\Lib\site-packages\httpcore\_async\socks_proxy.py", line 232, in handle_async_request
    stream = await self._network_backend.connect_tcp(**kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\danil\Desktop\ProjectsPython\HamsterKeys\venv\Lib\site-packages\httpcore\_backends\auto.py", line 30, in connect_tcp
    return await self._backend.connect_tcp(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\danil\Desktop\ProjectsPython\HamsterKeys\venv\Lib\site-packages\httpcore\_backends\anyio.py", line 114, in connect_tcp
    with map_exceptions(exc_map):
  File "C:\Users\danil\AppData\Local\Programs\Python\Python312\Lib\contextlib.py", line 158, in __exit__
    self.gen.throw(value)
  File "C:\Users\danil\Desktop\ProjectsPython\HamsterKeys\venv\Lib\site-packages\httpcore\_exceptions.py", line 14, in map_exceptions
    raise to_exc(exc) from exc
httpcore.ConnectTimeout

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\danil\Desktop\ProjectsPython\HamsterKeys\main.py", line 144, in <module>
    keys, game_name = asyncio.run(main(game_choice, key_count, proxy))
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\danil\AppData\Local\Programs\Python\Python312\Lib\asyncio\runners.py", line 194, in run
    return runner.run(main)
           ^^^^^^^^^^^^^^^^
  File "C:\Users\danil\AppData\Local\Programs\Python\Python312\Lib\asyncio\runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\danil\AppData\Local\Programs\Python\Python312\Lib\asyncio\base_events.py", line 687, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "C:\Users\danil\Desktop\ProjectsPython\HamsterKeys\main.py", line 129, in main
    keys = await asyncio.gather(*tasks)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\danil\Desktop\ProjectsPython\HamsterKeys\main.py", line 103, in generate_key_process
    client_token = await login(client_id, app_token, proxy)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\danil\Desktop\ProjectsPython\HamsterKeys\main.py", line 67, in login
    response = await client.post(
               ^^^^^^^^^^^^^^^^^^
  File "C:\Users\danil\Desktop\ProjectsPython\HamsterKeys\venv\Lib\site-packages\httpx\_client.py", line 1892, in post
    return await self.request(
           ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\danil\Desktop\ProjectsPython\HamsterKeys\venv\Lib\site-packages\httpx\_client.py", line 1574, in request
    return await self.send(request, auth=auth, follow_redirects=follow_redirects)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\danil\Desktop\ProjectsPython\HamsterKeys\venv\Lib\site-packages\httpx\_client.py", line 1661, in send
    response = await self._send_handling_auth(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\danil\Desktop\ProjectsPython\HamsterKeys\venv\Lib\site-packages\httpx\_client.py", line 1689, in _send_handling_auth
    response = await self._send_handling_redirects(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\danil\Desktop\ProjectsPython\HamsterKeys\venv\Lib\site-packages\httpx\_client.py", line 1726, in _send_handling_redirects
    response = await self._send_single_request(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\danil\Desktop\ProjectsPython\HamsterKeys\venv\Lib\site-packages\httpx\_client.py", line 1763, in _send_single_request
    response = await transport.handle_async_request(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\danil\Desktop\ProjectsPython\HamsterKeys\venv\Lib\site-packages\httpx\_transports\default.py", line 372, in handle_async_request
    with map_httpcore_exceptions():
  File "C:\Users\danil\AppData\Local\Programs\Python\Python312\Lib\contextlib.py", line 158, in __exit__
    self.gen.throw(value)
  File "C:\Users\danil\Desktop\ProjectsPython\HamsterKeys\venv\Lib\site-packages\httpx\_transports\default.py", line 86, in map_httpcore_exceptions
    raise mapped_exc(message) from exc
httpx.ConnectTimeout

**Comment by xaozzzz** [comment]
Maybe you need to make support for several proxies?

**Comment by ShafiqSadat** [comment]
I will update script and improve proxy support, ASAP!

**Comment by Adeboy901** [comment]
Please, what's the max key that can be generated with this script?

**Comment by ShafiqSadat** [comment]
Updated and added support for multi proxies!
