### ISSUE TITLE
How to fix it? What information should be in the proxy.txt file?

### ISSUE THREAD

**Issue by MeDieeen** [ShafiqSadat/HamsterKeyGen#9]
Select a game:
1: Riding Extreme 3D
2: Chain Cube 2048
3: My Clone Army
4: Train Miner
Enter the game number: 1
Enter the number of keys to generate: 2
Enter the proxy file path (leave empty to use 'proxy.txt'): 
2024-08-07 00:15:26 | INFO     | 143 - Generating 2 key(s) for Riding Extreme 3D using proxy from proxy.txt
Traceback (most recent call last):
  File "/home/runner/Key/.pythonlibs/lib/python3.10/site-packages/httpx/_transports/default.py", line 69, in map_httpcore_exceptions
    yield
  File "/home/runner/Key/.pythonlibs/lib/python3.10/site-packages/httpx/_transports/default.py", line 373, in handle_async_request
    resp = await self._pool.handle_async_request(req)
  File "/home/runner/Key/.pythonlibs/lib/python3.10/site-packages/httpcore/_async/connection_pool.py", line 216, in handle_async_request
    raise exc from None
  File "/home/runner/Key/.pythonlibs/lib/python3.10/site-packages/httpcore/_async/connection_pool.py", line 196, in handle_async_request
    response = await connection.handle_async_request(
  File "/home/runner/Key/.pythonlibs/lib/python3.10/site-packages/httpcore/_async/http_proxy.py", line 289, in handle_async_request
    connect_response = await self._connection.handle_async_request(
  File "/home/runner/Key/.pythonlibs/lib/python3.10/site-packages/httpcore/_async/connection.py", line 99, in handle_async_request
    raise exc
  File "/home/runner/Key/.pythonlibs/lib/python3.10/site-packages/httpcore/_async/connection.py", line 76, in handle_async_request
    stream = await self._connect(request)
  File "/home/runner/Key/.pythonlibs/lib/python3.10/site-packages/httpcore/_async/connection.py", line 122, in _connect
    stream = await self._network_backend.connect_tcp(**kwargs)
  File "/home/runner/Key/.pythonlibs/lib/python3.10/site-packages/httpcore/_backends/auto.py", line 30, in connect_tcp
    return await self._backend.connect_tcp(
  File "/home/runner/Key/.pythonlibs/lib/python3.10/site-packages/httpcore/_backends/anyio.py", line 114, in connect_tcp
    with map_exceptions(exc_map):
  File "/nix/store/rwxj49zghamyhy07b67yhiq64bmznvmm-python3-3.10.14/lib/python3.10/contextlib.py", line 153, in __exit__
    self.gen.throw(typ, value, traceback)
  File "/home/runner/Key/.pythonlibs/lib/python3.10/site-packages/httpcore/_exceptions.py", line 14, in map_exceptions
    raise to_exc(exc) from exc
httpcore.ConnectError: [Errno -2] Name or service not known

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/runner/Key/main.py", line 144, in <module>
    keys, game_name = asyncio.run(main(game_choice, key_count, proxy))
  File "/nix/store/rwxj49zghamyhy07b67yhiq64bmznvmm-python3-3.10.14/lib/python3.10/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/nix/store/rwxj49zghamyhy07b67yhiq64bmznvmm-python3-3.10.14/lib/python3.10/asyncio/base_events.py", line 649, in run_until_complete
    return future.result()
  File "/home/runner/Key/main.py", line 129, in main
    keys = await asyncio.gather(*tasks)
  File "/home/runner/Key/main.py", line 103, in generate_key_process
    client_token = await login(client_id, app_token, proxy)
  File "/home/runner/Key/main.py", line 67, in login
    response = await client.post(
  File "/home/runner/Key/.pythonlibs/lib/python3.10/site-packages/httpx/_client.py", line 1892, in post
    return await self.request(
  File "/home/runner/Key/.pythonlibs/lib/python3.10/site-packages/httpx/_client.py", line 1574, in request
    return await self.send(request, auth=auth, follow_redirects=follow_redirects)
  File "/home/runner/Key/.pythonlibs/lib/python3.10/site-packages/httpx/_client.py", line 1661, in send
    response = await self._send_handling_auth(
  File "/home/runner/Key/.pythonlibs/lib/python3.10/site-packages/httpx/_client.py", line 1689, in _send_handling_auth
    response = await self._send_handling_redirects(
  File "/home/runner/Key/.pythonlibs/lib/python3.10/site-packages/httpx/_client.py", line 1726, in _send_handling_redirects
    response = await self._send_single_request(request)
  File "/home/runner/Key/.pythonlibs/lib/python3.10/site-packages/httpx/_client.py", line 1763, in _send_single_request
    response = await transport.handle_async_request(request)
  File "/home/runner/Key/.pythonlibs/lib/python3.10/site-packages/httpx/_transports/default.py", line 372, in handle_async_request
    with map_httpcore_exceptions():
  File "/nix/store/rwxj49zghamyhy07b67yhiq64bmznvmm-python3-3.10.14/lib/python3.10/contextlib.py", line 153, in __exit__
    self.gen.throw(typ, value, traceback)
  File "/home/runner/Key/.pythonlibs/lib/python3.10/site-packages/httpx/_transports/default.py", line 86, in map_httpcore_exceptions
    raise mapped_exc(message) from exc
httpx.ConnectError: [Errno -2] Name or service not known

**Comment by ShafiqSadat** [comment]
Please read readme file, also updated for support multi proxies from file!

```sh
git pull
```

Please run above command!
